confutils.nim, confutils/shell_completion.nim
Here's a working protoype that seems to work just fine with my synthetic test case.
In order to do as much as possible using Nim (that is, without creating any intermediate shell script) the completion protocol defined by [Bash](https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion.html) is employed, it doesn't allow us to do fancy completion tricks but allows us to support Bash, Zsh and possibly any other compatible shell without adding more code/complexity.
The `ShellLexer` is needed to "parse" the input string and it does pass all the test-cases (courtesy of CPython `shlex` module).
- I plan on adding another `pragma` to allow the user to specify a custom set of completions
```sh
autoload -Uz bashcompinit && bashcompinit
complete -C <binary-path> <command-name>
``` …
=> Initial support for command-line completion

confutils.nim
```text
./tests/cli_example --foo:1 --bar:a --withBaz --foo:2 --bar:boo --bar:hoo --withBaz:false
foo = 2
bar = hoo
baz = false
```
=> allow repeating an option to override its value

confutils.nim, confutils/config_file.nim, confutils/envvar/envvar_serialization.nim, confutils/envvar/reader.nim, confutils/winreg/reader.nim, confutils/winreg/utils.nim, tests/config_files/current_user/testVendor/testApp.toml, tests/config_files/system_wide/testVendor/testApp.toml, tests/test_all.nim, tests/test_config_file.nim
deviation from README.md plan:
* `appName`, `vendorName`: instead of passing them as parameter to `load`, they are overrideable proc.
* I don't really get the hang of `configFileEnumerator`. My approach is the user need to register which type of config file they need, along with file ext and path. Env var and windows registry also become optional instead of forced to the user.
* env var prefix not passed as parameter to `load` but it is registered along with config file format.
* `envTable`, `EnvValuesFormat`, and `ConfigFileFormat` parameters are not covered in this implementation.
=> Config file integration

confutils.nim
Recent addition of config_file to confutils now require clients importing `confutils` to load configuration files to also import `options`. Rather than adding this import everywhere, it may be better to simply export `options` from `confutils`.
=> Added exporting of std/options

confutils.nim, confutils.nimble, tests/fail/test_abbr_duplicate_root.nim, tests/fail/test_abbr_duplicate_root_subcommand.nim, tests/fail/test_abbr_duplicate_subcommand.nim, tests/fail/test_name_duplicate_root.nim, tests/fail/test_name_duplicate_root_subcommand.nim, tests/fail/test_name_duplicate_subcommand.nim, tests/test_duplicates.nim
How the algorithm works:
- Recursive depth first search from root to target node, where the target node is the current subcmd housing the new opt.
- What we want is find relevant path and discard other path.
- After we find the correct path from root to target subcmd. then we search for duplicate in this hierarchy of subcommand.
- If duplicate found, compilation will terminate with error message.
- Other non-relevant path might have the same abbr or name with current opt, but that is not a problem, a duplicate in other hierarchy path is allowed.
- The only place where all path must respect no duplication is the root node.
This additional feature is short and simple, but accompanied by quite a lot of tests, hence the number of files also not few.
=> add compile time check to detect duplicate abbr and duplicate name

README.md, confutils.nim, confutils/defs.nim
line break char: '\n', '\r'
example:
```text
-x, --name   regular description [=defVal].
longdesc line one.
longdesc line two.
longdesc line three.
```
why additional pragma?
- to keep the default value not too far away from the 'name'.
=> feature: multiple lines long description

confutils.nim, confutils/defs.nim, tests/test_all.nim, tests/test_ignore.nim
you can still set the value of a hidden option,
it just dont show up in the help text.
but using `ignore`, the is no chance you can set the value from cli.
=> feature: add `ignore` property in addition to `hidden`

confutils.nim, tests/test_all.nim, tests/test_parsecmdarg.nim
Fix https://github.com/status-im/nim-confutils/issues/43
=> add parseCmdArg tests; fix 64-bit int parsing on 32-bit platforms

README.md, confutils.nim, confutils/cli_parser.nim, confutils/defs.nim, confutils/std/net.nim, tests/test_config_file.nim, tests/test_qualified_ident.nim
- use plain `string` everywhere in place of deprecated https://nim-lang.org/docs/system.html#TaintedString which generates lots of warnings when building Nimbus with Nim 1.6.
In Nim 1.6, a `TaintedString` is a string:
```nim
type TaintedString* {.deprecated: "Deprecated since 1.5".} = string
```
so this has no effect.
In Nim 1.2 and Nim 1.4, it's a normal string unless `taintMode` is defined, which at least in `nimbus-eth2`, does not happen:
```nim
when taintMode:
type TaintedString* = distinct string ## A distinct string type that
```
Furthermore, the all the `TaintedString`/`string` conversions I found did no validity checking at all, just treated this as one more (in reality, nonexistent) roadbump to bulldoze through the type system. This includes all the couple dozen Status Nimbus git …
=> rm TaintedString for string; some proc -> func

.github/workflows/ci.yml, confutils.nim, confutils.nimble
https://github.com/nim-lang/Nim/pull/21611 means that `nim-confutils` has UB before Nim 1.6 regardless.
=> remove support for Nim v1.2 and v1.4

confutils.nim, confutils/config_file.nim
For the `parseCmdArg` that may fail with `ValueError`, add annotations.
=> annotate `parseCmdArg` with `{.raises.}`

confutils.nim
The `appInvocation` template in `confutils` is used while showing help, e.g., before quitting. To ensure that `quit` actually happens, it can't raise exceptions. Fix that by falling back to `""` on `OSError`.
=> catch exceptions in `appInvocation`

confutils.nim
We use `%` and `&` to format some strings, which may raise `ValueError` if the format string is weird. As we are using them in ways that should always succeed, catch those `ValueError` and convert to asserts.
=> suppress unreachable string format errors

confutils.nim
Value parsers are currently allowed to raise `CatchableError`, but in practice only `ValueError` is raised. Restrict to `ValueError`, and also properly convert them to `fail` / `ConfigurationError` if applicable.
=> restrict `parseCmdArgAux` to `ValueError`

confutils/shell_completion.nim
When `COMP_POINT` is invalid or out of range, return an empty list of completions instead of raising `ValueError`. This matches behaviour for `comp_point < 0 or comp_point > len(comp_line)` cases.
=> return empty completion lines on unsupported `COMP_POINT`

confutils.nim, tests/test_config_file.nim
The way how `secondarySources` are used in `status-im/nimbus-eth2`, they call `addConfigFile` again which may raise `ConfigurationError`. When that happened, loading the primary config file didn't result in `fail`, which differs in error handling from errors within itself as opposed to within `secondarySources`. To keep callers concise, apply same error handling behaviour regardless of whether the error occurred during primary or secondary sources processing.
=> fail on error while processing `secondarySources`

confutils/winreg/writer.nim, tests/test_winreg.nim
Tag `writeValue` override with `{.raises: [IOError].}`.
=> add `{.raises.}` annotation to `writeValue`

confutils.nim
In Nim 2.0, `'result' requires explicit initialization`.
Fix `makeDefaultValue` to do so.
=> explicitly initialize `result`

confutils/std/net.nim
`completeCmdArg` does nothing equally well on `IpAddress` now.
=> add `IpAddress` equivalents for `ValidIpAddress` support

confutils.nim
`addConfigFileContent` can raise `ConfigurationError`. Declare so.
=> add missing `{.raises.}` to `addConfigFileContent`

confutils.nim, confutils.nimble
When calling `cli` macro from nimscript, there are compilation issues:
- `nim-faststreams` is not available, therefore, `nim-serialization` does not work, due to `equalMem` being gated behind `notJSnotNims`. Dropping support for config files in nimscript contexts fixes that.
- `std/strformat` raises `ValueError` for invalid format strings, but does so at runtime rather than checking types at compiletime. As it is only used for simple string concatenation in error cases, changing to simple concatenation avoids verbose error handling.
- `getAppFilename()` is unavailable in `nimscript`. This was already fixed by replacing it with `appInvocation()` but two instances of direct `getAppFilename()` calls remained in default arguments. This is fixed by changing those default arguments as well.
- …
=> Fix `cli` invocation from nimscript
